/**
 * Represents a payment request to the eSewa payment gateway.
 */
interface EsawaPaymentRequest {
  /** Amount of the product. */
  amount: number;

  /** Tax amount applied to the product. */
  tax_amount: number;

  /** Service charge by the merchant on the product. */
  product_service_charge: number;

  /** Delivery charge by the merchant on the product. */
  product_delivery_charge: number;

  /** Unique code provided by eSewa for the merchant product. */
  product_code: string;

  /**
   * Total payment amount, including tax, service, and delivery charges.
   * Calculated as: total_amount = amount + tax_amount + product_service_charge + product_delivery_charge
   */
  total_amount: number;

  /** A unique ID for the transaction (use alphanumeric characters and hyphens only). */
  transaction_uuid: string;

  /** URL where the customer will be redirected after a successful transaction. */
  success_url: string;

  /** URL where the customer will be redirected after a failed or pending transaction. */
  failure_url: string;

  /** Unique field names used to generate the signature. */
  signed_field_names: string;

  /** HMAC signature generated to ensure data integrity. */
  signature: string;
}

/**
 * Represents a successful payment response from eSewa.
 */
interface EsawaSuccessResponse {
  /** Status of the transaction (will always be "COMPLETE" for successful payments). */
  status: "COMPLETE";

  /** Signature to verify the integrity of the response.  */
  signature: string;

  /** Unique transaction code generated by eSewa. */
  transaction_code: string;

  /** Total amount of the transaction. */
  total_amount: number;

  /** Unique transaction ID.  */
  transaction_uuid: string;

  /** Product code for the purchased item. */
  product_code: string;

  /** The URL the user was redirected to after success. */
  success_url: string;

  /** Field names included in the signature calculation. */
  signed_field_names: string;
}

/**
 * Represents the possible responses from the eSewa status check API.
 */
type EsawaStatusCheckResponse =
  | { status: "PENDING" | "NOT_FOUND"; refId: null }
  | { status: "COMPLETE" | "CANCELED"; refId: string }
  | { status: "FULL_REFUND" | "PARTIAL_REFUND" | "AMBIGUOUS"; refId: string }
  | { code: number; error_message: string };
